### PR TITLE
fixed custom farmland compat

### LINKED ISSUE #665: [1.15.1] Plant sower doesn't plant on custom farmlands
Industrial Foregoing Version: 2.2.0
TeslaCoreLib Version: 2.3.4
[This](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/58c83806b975e05a5d2d3b4e58e9e394f8114ad9#diff-da45ad8e1a131f0d26f33eb565a14448) didn't fix the problem with custom farmland.

### PR DESCRIPTION
**Pull request by MelanX**
closes #665

### CODE REVIEW

File: src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/PlantSowerTile.java [hunk 1]
```diff
@@ -68,7 +68,8 @@ public WorkAction work() {
             }
             if (!stack.isEmpty() && stack.getItem() instanceof BlockItem && ((BlockItem) stack.getItem()).getBlock() instanceof IPlantable) {
                 Block block = ((BlockItem) stack.getItem()).getBlock();
-                if (block.canSustainPlant(this.world.getBlockState(pos.down()), world, pos, Direction.UP, (IPlantable) block)) {
+                Block soil = this.world.getBlockState(pos.down()).getBlock();
+                if (soil.canSustainPlant(this.world.getBlockState(pos.down()), world, pos, Direction.UP, (IPlantable) block)) {
```
Comment (pupnewfster) [inline src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/PlantSowerTile.java]: Wouldn't it be better/cleaner to do this as:
```java
if (this.world.getBlockState(pos.down()).canSustainPlant(world, pos, Direction.UP, (IPlantable) block)) {
```
Even though I think it really should be:
```java
if (this.world.getBlockState(pos.down()).canSustainPlant(world, pos.down(), Direction.UP, (IPlantable) block)) {
```

Comment (MelanX) [reply src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/PlantSowerTile.java]: I tried with custom farmland and it worked. If Buuz don’t want the variable, he can just do it on his own and close this PR. It’s not very much code :)

Comment (pupnewfster) [reply src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/PlantSowerTile.java]: The main thing with the secondary line, that I think is correct, is also to make sure that it fixes it to be giving the custom farmland the  proper position it is at.

**Comment by MelanX** [comment]
I can try with the second line in ~10 hours.

File: src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/PlantSowerTile.java (hunk 1 above)
Comment (MelanX) [reply src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/PlantSowerTile.java]: Oh, with mobile phone it commented at the wrong place. I tried both methods and both are working.. I'll push the second version. Buuz can just close this PR because I commited too much :D it's just for him to see the final code.
